apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: webhook-source-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: webhook-source
    properties:
      subpath: customer
  sink:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: my-topic